### ISSUE TITLE
Language server lsp-vue has crashed, do you want to restart it?

### ISSUE THREAD

**Issue by Guanqing-cool** [sublimelsp/LSP-vue#23] opened 2020-04-12 15:18 UTC
After downloading the lsp-vue , I can't use it. Open the Vue file and the message "language server LSP Vue has crashed, do you want to restart it?". It's still useless to restart it. What causes the language server to fail?And how do I fix it。

**Comment by rchl** [comment] 2020-04-12 21:12
Check ST console and `LSP: Toggle Log Panel` for any relevant errors or paste here.

**Comment by Guanqing-cool** [comment] 2020-04-12 23:39
Sorry, the console doesn't seem to show any errors. It's just a sublime text window that pops up when the Vue file is loaded about a problem with the language server. This is my screenshot of the problem.

<img width="608" alt="Snipaste_2020-04-13_07-23-08" src="https://user-images.githubusercontent.com/63550611/79082561-9266e680-7d59-11ea-83ad-69c74b26b757.png">

**Comment by Guanqing-cool** [comment] 2020-04-13 04:47
> Check ST console and `LSP: Toggle Log Panel` for any relevant errors or paste here.

Sorry, the console doesn't seem to show any errors. It's just a sublime text window that pops up when the Vue file is loaded about a problem with the language server. This is my screenshot of the problem.
<img width="608" alt="error" src="https://user-images.githubusercontent.com/63550611/79092874-dcb18d00-7d84-11ea-804e-df6b483c58e7.png">

**Comment by rchl** [comment] 2020-04-13 05:42
Check also the other log panel that I've mentioned. You can open it from command palette.

And the contents of Vue file can also be the reason.

**Comment by Guanqing-cool** [comment] 2020-04-13 05:59
> Check also the other log panel that I've mentioned. You can open it from command palette.
> 
> And the contents of Vue file can also be the reason.

OK, I switched to the log panel with two messages:
lsp-vue: Loaded bundled typescript@3.7.4.
lsp-vue: Vetur initialized
<img width="627" alt="toggle log  panel" src="https://user-images.githubusercontent.com/63550611/79096172-f6f06880-7d8e-11ea-9392-2d42f20335c4.png">

**Comment by rchl** [comment] 2020-04-13 06:25
That still doesn't tell us anything.
I saw part off the Vue file in your screenshot and it looked rather weird - you were initialising Vue there which you wouldn't typically do in a Vur file.
Are you able to share the file or whole repo?

**Comment by Guanqing-cool** [comment] 2020-04-13 08:12
> That still doesn't tell us anything.
> I saw part off the Vue file in your screenshot and it looked rather weird - you were initialising Vue there which you wouldn't typically do in a Vue file.
> Are you able to share the file or whole repo?

Thank you for your sincere answer to my question.
At first, in order to test lsp-vue, I just changed the HTML file to Vue file directly.
After your guidance, I used vue cli to create a simple Vue project in cmd. 
However, when I used sublime to open the vue file in the project, the previous problems still 
occurred.
Do Vue files need any other conditions or environments？
<img width="952" alt="new vue file" src="https://user-images.githubusercontent.com/63550611/79104508-52c3ed00-7da1-11ea-8d16-e2999b5c277e.png">

**Comment by rwols** [comment] 2020-04-13 08:18
Did you try removing the Vetur language server from Sublime’s Cache dir? Perhaps the installation did not succeed. When Vetur is removed, this package will re-install it.

**Comment by rchl** [comment] 2020-04-13 08:23
It's probably easier to just reinstall lsp-vue package than hunting the cache directory. That will also clear the cache.

There is one thing I forgot to mention before... To possibly see the error that vetur throws, you also h

**Comment by Guanqing-cool** [comment] 2020-04-13 09:03
> It's probably easier to just reinstall lsp-vue package than hunting the cache directory. That will also clear the cache.
> 
> There is one thing I forgot to mention before... To possibly see the error that vetur throws, you also should enable all `log_*` settings in LSP preferences.

I set all logs in LSP to true. Here is the information about console and log panel. But I still don't understand the problem.
Console:
LSP: received config lsp-vue from LspVuePlugin
LSP: global configs ['lsp-vue=True', 'metals=False', 'cquery=False', 'haskell-ide-engine=False', 'rls=False', 'polymer-ide=False', 'flow=False', 'rust-analyzer=False', 'javascript-typescript-langserver=False', 'gopls=False', 'reason=False', 'rlang=False', 'elixir-ls=False', 'erlang-ls=False', 'sorbet=False', 'jdtls=False', 'intelephense-ls=False', 'vscode-css=False', 'pyls=False', 'bashls=False', 'phpls=False', 'dart=False', 'ocaml=False', 'golsp=False', 'lsp-tsserver=False', 'typescript-language-server=False', 'ruby=False', 'sourcekit-lsp=False', 'clangd=False']
LSP: group 0 view C:\Users\Zhu Guanqing\Desktop\code\my-vue\src\App.vue
LSP: window 2 starting 1 initial views
LSP: window 2 requests lsp-vue for C:\Users\Zhu Guanqing\Desktop\code\my-vue\src\App.vue
LSP: starting ['node', 'C:\\Users\\Zhu Guanqing\\Desktop\\temp\\Sublime Text Build 3211 x64\\Data\\Cache\\LSP-vue\\server\\node_modules\\vue-language-server\\bin\\vls', '--stdio']
LSP: window 2 added session lsp-vue
Unable to fetch update url contents
LSP: single folder session: C:\Users\Zhu Guanqing\Desktop\code
Package Control: Skipping automatic upgrade, last run at 2020-04-13 16:37:44, next run at 2020-04-13 17:37:44 or after
LSP: process 10504 stdout ended (still alive)
LSP: LSP stream logger stopped.
LSP: process 10504 exited with code 1
LSP: transport failed
LSP: unable to send textDocument/hover
LSP: unable to send textDocument/hover
Unable to open /C/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Packages/LSP/LSP.sublime-settings

Log Panel:
:: --> lsp-vue initialize(1): {'workspaceFolders': [{'uri': 'file:///C:/Users/Zhu%20Guanqing/Desktop/code', 'name': 'code'}], 'processId': 10560, 'clientInfo': {'name': 'Sublime Text LSP'}, 'capabilities': {'workspace': {'workspaceFolders': True, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'configuration': True, 'didChangeConfiguration': {}, 'executeCommand': {}, 'applyEdit': True}, 'textDocument': {'references': {}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'rename': {}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'declaration': {'linkSupport': True}, 'synchronization': {'willSaveWaitUntil': True, 'didSave': True, 'willSave': True}, 'documentHighlight': {}, 'publishDiagnostics': {'relatedInformation': True}, 'colorProvider': {}, 'implementation': {'linkSupport': True}, 'rangeFormatting': {}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'formatting': {}, 'completion': {'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'completionItem': {'snippetSupport': True}}, 'definition': {'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'typeDefinition': {'linkSupport': True}}}, 'rootPath': 'C:\\Users\\Zhu Guanqing\\Desktop\\code', 'initializationOptions': {'config': {'css': {}, 'emmet': {}, 'javascript': {'format': {}}, 'stylusSupremacy': {}, 'vetur': {'experimental': {'templateInterpolationService': True}, 'format': {'scriptInitialIndent': False, 'enable': True, 'defaultFormatterOptions': {}, 'defaultFormatter': {'js': 'none', 'ts': 'none'}, 'options': {'useTabs': False, 'tabSize': 2}, 'styleInitialIndent': False}, 'validation': {'template': True, 'script': True, 'style': True}, 'completion': {'tagCasing': 'kebab', 'useScaffoldSnippets': False, 'autoImport': False}, 'useWorkspaceDependencies': False}, 'html': {'suggest': {}}, 'typescript': {'format': {}}}}, 'rootUri': 'file:///C:/Users/Zhu%20Guanqing/Desktop/code'}
lsp-vue: Loaded bundled typescript@3.7.4.
lsp-vue: Vetur initialized
:: <<< lsp-vue 1: {'capabilities': {'documentFormattingProvider': False, 'codeActionProvider': True, 'documentLinkProvider': {'resolveProvider': False}, 'documentSymbolProvider': True, 'definitionProvider': True, 'completionProvider': {'resolveProvider': True, 'triggerCharacters': ['.', ':', '<', '"', "'", '/', '@', '*']}, 'hoverProvider': True, 'colorProvider': True, 'textDocumentSync': 1, 'documentHighlightProvider': True, 'referencesProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(']}}}
::  -> lsp-vue initialized: {}
::  -> lsp-vue textDocument/didOpen
lsp-vue: C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\typescript\lib\typescript.js:131040
lsp-vue: throw error;
lsp-vue: ^
lsp-vue: 
lsp-vue: Error: Could not find source file: 'c:\Users\Zhu Guanqing\Desktop\code\my-vue\src\App.vue.template'.
lsp-vue: at getValidSourceFile (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\typescript\lib\typescript.js:131036:29)
lsp-vue: at Object.getSemanticDiagnostics (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\typescript\lib\typescript.js:131258:36)
lsp-vue: at VueInterpolationMode.doValidation (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\modes\template\interpolationMode.js:38:56)
lsp-vue: at VueHTMLMode.doValidation (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\modes\template\index.js:21:86)
lsp-vue: at C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\services\vls.js:366:51
lsp-vue: at Array.forEach (<anonymous>)
lsp-vue: at VLS.doValidate (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\services\vls.js:364:72)
lsp-vue: at VLS.validateTextDocument (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\services\vls.js:358:34)
lsp-vue: at Timeout._onTimeout (C:\Users\Zhu Guanqing\Desktop\temp\Sublime Text Build 3211 x64\Data\Cache\LSP-vue\server\node_modules\vue-language-server\dist\services\vls.js:347:18)
lsp-vue: at listOnTimeout (internal/timers.js:531:17) {
lsp-vue: ProgramFiles: [
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es5.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2016.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.dom.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.core.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.collection.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.generator.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.promise.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.object.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.string.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.intl.d.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Cache/LSP-vue/server/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
lsp-vue: 'vue-temp/vue-editor-bridge.ts',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/code/my-vue/src/App.vue',
lsp-vue: 'C:/Users/Zhu Guanqing/Desktop/code/my-vue/src/App.vue.template'
lsp-vue: ]
lsp-vue: }

**Comment by Guanqing-cool** [comment] 2020-04-13 09:14
> Did you try removing the Vetur language server from Sublime’s Cache dir? Perhaps the installation did not succeed. When Vetur is removed, this package will re-install it.

In sublime's cash directory, I did not find the vetur language server. There is a folder called vue -language -server. In its subdirectory, there is the vetursnippets folder.
I tried to reinstall lsp-vue many times, but it still didn't work.

**Comment by rwols** [comment] 2020-04-13 09:27
From your logs:
```
lsp-vue: throw error;
lsp-vue: ^
lsp-vue:
lsp-vue: Error: Could not find source file: 'c:\Users\Zhu Guanqing\Desktop\code\my-vue\src\App.vue.template'.
```
Is the file `App.vue.template` present?

**Comment by rchl** [comment] 2020-04-13 09:28
I don't think it's really supposed to be present on a typical Vue app. Would have to look at vetur code to see why it's expecting that.

**Comment by rchl** [comment] 2020-04-13 09:58
@Guanqing-cool could you first sort out some more fundamental issues like:
```
Unable to open /C/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Packages/LSP/LSP.sublime-settings
```
?
There is something wrong with accessing files on your system. Possibly because you have everything under `Desktop` which might have special permission handling.

Maybe install ST properly in Program Files and then try it out again. Could also move your project to user's Documents for example.

**Comment by rchl** [comment] 2020-04-13 10:02
It's also suspicious that you have LSP installed in `Packages`. It should be installed in `Installed Packages` if you install it normally through Package Control.

**Comment by Guanqing-cool** [comment] 2020-04-13 10:20
> It's also suspicious that you have LSP installed in `Packages`. It should be installed in `Installed Packages` if you install it normally through Package Control.

I'm sure I installed it from Package Control in the normal way.  I only have three plug-ins installed:
LSP  ,Vue Syntax Highlight , lsp-vue
<img width="281" alt="installed package" src="https://user-images.githubusercontent.com/63550611/79113407-7132e400-7db3-11ea-9a26-482306b5fd55.png">
<img width="282" alt="packages" src="https://user-images.githubusercontent.com/63550611/79113426-7859f200-7db3-11ea-9e3f-05b53368820b.png">

**Comment by Guanqing-cool** [comment] 2020-04-13 10:29
> @Guanqing-cool could you first sort out some more fundamental issues like:
> 
> ```
> Unable to open /C/Users/Zhu Guanqing/Desktop/temp/Sublime Text Build 3211 x64/Data/Packages/LSP/LSP.sublime-settings
> ```
> 
> ?
> There is something wrong with accessing files on your system. Possibly because you have everything under `Desktop` which might have special permission handling.
> 
> Maybe install ST properly in Program Files and then try it out again. Could also move your project to user's Documents for example.

I also installed sublime on disk D, but it still have the same problem. Is it because I use the portable version of sublime?

**Comment by rchl** [comment] 2020-04-13 10:43
What version of node are you running?

**Comment by Guanqing-cool** [comment] 2020-04-13 10:54
> What version of node are you running?

v12.14.1

**Comment by rchl** [comment] 2020-04-13 14:38
I'm running the same vetur code, tried same node version and same lsp-vue settings and still can't reproduce.

The error about `App.vue.template` is confusing because that file is not supposed to exist physically. It's created "virtually" by vetur and passed to typescript for parsing. That parsing fails for you somehow. Not sure what's the actual issue there.

**Comment by rchl** [comment] 2020-04-13 19:58
I've booted my Windows machine and was actually able to reproduce easily there.

Turns out the new version of VLS doesn't crash so I've created PR update to latest version - #24

**Comment by kapitanluffy** [comment] 2020-04-28 08:20
I made it work for now by using the `vls` binary found in my path. Here's my [fork](https://github.com/kapitanluffy/LSP-vue/tree/refactor/vls-no-depend)

If the `vls` binary does not work, You may need to manually compile [vetur server](https://github.com/vuejs/vetur/tree/master/server). 
The latest vls version (`0.2.0`) also has this issue https://github.com/vuejs/vetur/issues/1840 (at least for me).

You will then need to manually use the newly compiled version in the plugin.
![image](https://user-images.githubusercontent.com/485799/80463944-9dca2c80-896b-11ea-99c6-5ad807f5c518.png)

It has an error in linking definitions from the template though. Everything else seem to work fine.
![image](https://user-images.githubusercontent.com/485799/80463460-db7a8580-896a-11ea-87fd-0c822925a001.png)

It would be great if we can define the binary from the settings instead of relying for it to automatically install node dependencies in the background. I hope you can make yours work 😄

**Comment by rchl** [comment] 2020-04-28 08:25
The whole point of `LSP-vue` (and other `LSP-*` packages) is to handle dependencies for you. If you want to use your local dependency, just manually configure LSP like described in https://lsp.readthedocs.io/en/latest/#server-configuration . No need for `LSP-vue` then.

We know that new version has another crashing issue, that's why we are holding up https://github.com/sublimelsp/LSP-vue/pull/24 . 
We could manually compile it, or add extra dependencies, but we'd rather avoid that extra work and just wait for upstream to release new version.

**Comment by rchl** [comment] 2020-07-22 20:26
Should be fixed in just released https://github.com/sublimelsp/LSP-vue/releases/tag/0.0.18

**Closed by rchl** 2020-07-22 20:26 UTC
